### ISSUE TITLE
Add missing validation message when language is not picked for an invitation

### ISSUE THREAD

**Issue by almirsarajcic** [3Stones-io/omedis#412]

**Comment by amos-kibet** [comment]
I have a similar issue as [this](https://github.com/phoenixframework/phoenix_live_view/issues/1109), where language input radio buttons are incorrectly displaying form validation errors when they haven't been visited yet. It seems to have been fixed, since now we are using `phx-feedback-for={@form[:language].name}` as suggested there, but it still doesn't work for me. Maybe I can try using JS hooks.

**Comment by amos-kibet** [comment]
I'm going to preselect language by using current user's language.
